default_vel_curve: 'trapezoid'
waypoints:
    - x: -0.33
      y: 0.0
      theta: -2.09
      time: 1.5
    - x: -0.66
      y: 0.0
      theta: -4.18
      time: 3.0
    - x: -1.0
      y: 0.0
      theta: 0.0
      time: 4.5
