default_vel_curve: 'trapezoid'
waypoints:
    - x: -1.0
      y: 1.0
      theta: 1.57
      time: 3.0
      control_points:
          - x: -0.1
            y: 0.9
    - x: -2.0
      y: 0.0
      theta: 3.16
      time: 6.0
      control_points:
          - x: -1.9
            y: 0.9
    - x: -1.0
      y: -1.0
      theta: -1.57
      time: 9.0
      control_points:
          - x: -1.9
            y: -0.9
    - x: 0.0
      y: 0.0
      theta: 0.0
      time: 12.0
      control_points:
          - x: -0.1
            y: -0.9
