default_vel_curve: 'trapezoid'
waypoints:
    - x: 0.3
      y: 0.0
      theta: 1.57
      time: 1.3
    - x: 0.3
      y: 0.0
      theta: 1.57
      time: 1.75
    - x: 0.6
      y: 0.0
      theta: 3.14
      time: 3.05
    - x: 0.6
      y: 0.0
      theta: 3.14
      time: 3.5
    - x: 0.0
      y: 0.0
      theta: 0.0
      time: 6.0
    - x: 0.0
      y: 0.0
      theta: 0.0
      time: 9.0
    - x: 0.1
      y: 0.0
      theta: 0.0
      time: 10.0
    - x: 0.1
      y: 0.0
      theta: 0.0
      time: 10.5
    - x: 0.2
      y: 0.0
      theta: 0.0
      time: 11.5
    - x: 0.2
      y: 0.0
      theta: 0.0
      time: 12.0
