default_vel_curve: trapezoid
waypoints:
  - x: 0.991
    y: 0.0
    theta: 2.217
    time: 2.0
    vel_curve: trapezoid
    control_points: None
  - x: 0.482
    y: 0.811
    theta: -2.123
    time: 4.0
    vel_curve: trapezoid
    control_points: None
  - x: -0.013
    y: 0.027
    theta: -0.014
    time: 6.0
    vel_curve: trapezoid
    control_points: None
