default_vel_curve: 'trapezoid'
waypoints:
    - x: 0.25
      y: 0.0
      theta: 0.0
      time: 0.5
    - x: 0.0
      y: 0.0
      theta: 0.0
      time: 1.0
    - x: -0.25
      y: 0.0
      theta: 0.0
      time: 1.5
    - x: 0.0
      y: 0.0
      theta: 0.0
      time: 2.0
