default_vel_curve: 'trapezoid'
waypoints:
    - x: -0.5
      y: -0.5
      theta: 1.57
      time: 1.9
      control_points:
          - x: -0.5
            y: 0.0
    - x: -1.0
      y: 0.0
      theta: 3.14
      time: 3.8
      control_points:
          - x: -0.5
            y: 0.0
    - x: -0.7
      y: 0
      theta: -1.05
      time: 4.9
    - x: -0.7
      y: 0
      theta: -1.05
      time: 5.2
    - x: -0.4
      y: 0.0
      theta: 1.04
      time: 6.5
    - x: -0.4
      y: 0.0
      theta: 1.04
      time: 6.8
    - x: 0.0
      y: 0.0
      theta: 3.14
      time: 8.0
    - x: 0.0
      y: 0.0
      theta: 3.14
      time: 8.25
