default_vel_curve: 'linear'
waypoints:
    - x: 6.0
      y: 0.0
      theta: 0.0
      time: 10.0
      control_points:
          - x: 1.0
            y: 5.0
          # - x: 3.0
          #   y: -5.0
          # - x: 5.0
          #   y: 5.0
