default_vel_curve: 'trapezoid'
waypoints:
    - x: 0.7
      y: -0.7
      theta: 4.72
      time: 4.0
      control_points:
          - x: 0.7
            y: 0.0
    - x: 1.4
      y: 0.0
      theta: 3.14
      time: 8.0
      control_points:
          - x: 0.7
            y: 0.0
    - x: 0.7
      y: 0.7
      theta: 1.57
      time: 12.0
      control_points:
          - x: 0.7
            y: 0.0
    - x: 0.0
      y: 0.0
      theta: 0.0
      time: 16.0
      control_points:
          - x: 0.7
            y: 0.0
