default_vel_curve: 'trapezoid'
waypoints:
    - x: 2.0
      y: -2.0
      theta: 4.72
      time: 4.0
      control_points:
          - x: 2.0
            y: 0.0
    - x: 4.0
      y: 0.0
      theta: 3.14
      time: 8.0
      control_points:
          - x: 2.0
            y: 0.0
    - x: 2.0
      y: 2.0
      theta: 1.57
      time: 12.0
      control_points:
          - x: 2.0
            y: 0.0
    - x: 0.0
      y: 0.0
      theta: 0.0
      time: 16.0
      control_points:
          - x: 2.0
            y: 0.0
