default_vel_curve: 'trapezoid'
waypoints:
    - x: -1.0
      y: 1.0
      theta: 1.57
      time: 3.0
      control_points:
          - x: -0.1
            y: 0.9
    - x: -0.9
      y: 1.1
      theta: 1.9
      time: 4.0
    - x: -1.1
      y: 1.1
      theta: 1.24
      time: 5.0
    - x: -1.0
      y: 1.0
      theta: 1.57
      time: 6.0
    - x: -2.0
      y: 0.0
      theta: 3.16
      time: 9.0
      control_points:
          - x: -1.9
            y: 0.9
