default_vel_curve: 'trapezoid'
waypoints:
    - x: 0.7
      y: -0.7
      theta: 4.72
      time: 2.0
      control_points:
          - x: 0.7
            y: 0.0
    - x: 1.4
      y: 0.0
      theta: 3.14
      time: 4.0
      control_points:
          - x: 0.7
            y: 0.0
    - x: 1.0
      y: 0
      theta: 0.85
      time: 5.5
    - x: 0.6
      y: 0.0
      theta: -0.85
      time: 6.5
    - x: 0.0
      y: 0.0
      theta: 3.14
      time: 8.25
