default_vel_curve: 'trapezoid'
waypoints:
    - x: 0.5
      y: 0.5
      theta: 1.0
      time: 1.75
    - x: 0.0
      y: 0.0
      theta: 0.0
      time: 3.5
    - x: 0.5
      y: -0.5
      theta: -1.0
      time: 5.25
    - x: 0.0
      y: 0.0
      theta: 0.0
      time: 7.0
