default_vel_curve: 'trapezoid'
waypoints:
    - x: 1.0
      y: 0.9
      theta: 1.57
      time: 3.5
      control_points:
          - x: 1.0
            y: 0.0
    - x: 1.0
      y: 0.9
      theta: 1.57
      time: 4.0
    - x: 1.0
      y: 1.0
      theta: 0.0
      time: 5.5
    - x: 1.0
      y: 1.0
      theta: 0.0
      time: 6.0
    - x: 1.0
      y: 1.1
      theta: -1.57
      time: 7.5
    - x: 1.0
      y: 1.1
      theta: -1.57
      time: 8.5
