waypoint_config_files:
    - circle_reverse_fast
    - circle_reverse_fast
    - circle_reverse_fast
    - forward_while_rotating
    - circle_reverse_fast
    - circle_reverse_fast
    - circle_reverse_fast
    - forward_while_rotating
