waypoint_config_files:
    - large_leaf
    - standstill
    - standstill
    - standstill
    - standstill
    - standstill
    - standstill_quarter
    - leaf
    - leaf
    - leaf
    - rotate_back
    #- large_leaf
    #- standstill
    #- standstill
    #- standstill
    #- leaf
    #- leaf
    #- leaf
    #- rotate_back
    #- large_leaf
    #- standstill
    #- standstill
    #- standstill
    #- standstill
    #- standstill
    #- standstill_quarter
    #- leaf
    #- leaf
    #- leaf
    #- rotate_back
