waypoint_config_files:
    - infinity_first_half
    - infinity_second_half
    - infinity_first_half_slow
    - infinity_second_half_slow
    - circle_reverse
    - circle_reverse
    - ending_1
    - standstill
    - standstill
    - standstill
    - standstill
    - triangle
    - reverse_triangle
    - triangle
    - reverse_triangle
    - zigzag_backward
    - rotate_180_degree
    - standstill_half
    - zigzag_forward
    - rotate_180_degree
    - standstill_half
    - ending_2
    - standstill
    - standstill
    - standstill
    - standstill
    - triangle
    - reverse_triangle
    - triangle
    - reverse_triangle
    - medium_fast
    - start_4
    - standstill
    - standstill
    - standstill
    - rotate_and_sideways
    - rotate_and_sideways
    - rotate_and_sideways
    - forward_and_backward
    - rotate_and_sideways
    - forward_and_backward
    - left_and_right    
    - standstill
    - standstill
    - standstill_half
    - rotate_and_sideways
    - rotate_and_sideways
    - rotate_and_sideways
    - forward_and_backward
    - rotate_and_sideways
    - forward_and_backward
    - left_and_right
    - sidestep
    - standstill
    - standstill
    - standstill
    - standstill
    - standstill_quarter
    - leaf
    - leaf
    - leaf
    - rotate_back
    - sidestep
    - standstill
    - standstill
    - standstill
    - standstill
    - standstill_quarter
    - leaf
    - leaf
    - leaf
    - rotate_back
    - standstill
    - standstill
    - rotate_and_sideways
    - rotate_and_sideways
    - rotate_and_sideways
    - forward_and_backward
    - rotate_and_sideways
    - forward_and_backward
    - left_and_right 
    - sidestep
    - standstill
    - standstill
    - standstill
    - standstill
    - standstill_quarter
    - leaf
    - leaf
    - leaf
    - rotate_back
    - ending_4
