waypoint_config_files:
    # infinity (0:24 - 1:43)
    - infinity_first_half
    - infinity_second_half
    - infinity_first_half_slow
    - infinity_second_half_slow
    - circle_reverse
    - circle_reverse
    - standstill
    - standstill
    - standstill
    # ending 1 (1:44 - 1:57)
    - ending_1
    - standstill
    - standstill
    # triangles (1:58 - 2:35)
    - standstill
    - standstill
    - standstill
    - triangle
    - reverse_triangle
    - triangle
    - reverse_triangle
    # zig zag (2:36 - 3:07)
    - zigzag_backward
    - rotate_180_degree
    - standstill_half
    - zigzag_forward
    - rotate_180_degree
    - standstill_half
    # ending 2 (3:08 - 3:11)
    - ending_2
    # triangles (3:12 - 3:49)
    - standstill_half
    - standstill
    - standstill
    - standstill
    - triangle
    - reverse_triangle
    - triangle
    - reverse_triangle
    - standstill
    - standstill
    # medium (3:50 - 4:27)
    - standstill
    - standstill_half
    - quarter_supereclipse
    - quarter_supereclipse_sharp
    - quarter_supereclipse
    - quarter_supereclipse_sharp
    # fast (4:28 - 4:59)
    - circle_reverse_fast
    - circle_reverse_fast
    - circle_reverse_fast
    - forward_while_rotating
    - circle_reverse_fast
    - circle_reverse_fast
    - circle_reverse_fast
    - forward_while_rotating
    - standstill_half
    # second medium (5:01 - 5:17)
    - quarter_supereclipse
    - quarter_supereclipse_sharp
      # second fast (5:18 - 5:33)
    - circle_reverse_fast
    - circle_reverse_fast
    - circle_reverse_fast
    - forward_while_rotating
    # start 4 (5:34 - 5:38)
    - start_4
    # rotate and sidways (5:39 - 6:14)
    - standstill
    - standstill
    - standstill
    - rotate_and_sideways
    - rotate_and_sideways
    - rotate_and_sideways
    - forward_and_backward
    - rotate_and_sideways
    - forward_and_backward
    - left_and_right    
    - standstill
    - standstill
    - standstill_half
    - rotate_and_sideways
    - rotate_and_sideways
    - rotate_and_sideways
    - forward_and_backward
    - rotate_and_sideways
    - forward_and_backward
    - left_and_right
    # leaf (6:15 - 7:09)
    - sidestep
    - standstill
    - standstill
    - standstill
    - standstill
    - standstill_quarter
    - leaf
    - leaf
    - leaf
    - rotate_back
    - sidestep
    - standstill
    - standstill
    - standstill
    - standstill
    - standstill_quarter
    - leaf
    - leaf
    - leaf
    - rotate_back
    # rotate and sidways (7:10 - 7:25)
    - standstill
    - standstill
    - rotate_and_sideways
    - rotate_and_sideways
    - rotate_and_sideways
    - forward_and_backward
    - rotate_and_sideways
    - forward_and_backward
    - left_and_right 
      # leaf (7:26 - 7:54)
    - sidestep
    - standstill
    - standstill
    - standstill
    - standstill
    - standstill_quarter
    - leaf
    - leaf
    - leaf
    - rotate_back
    # ending 4 (7:55 - 8:01)
    - ending_4
