#! /usr/bin/env python

from __future__ import print_function

import os
import rospy
import traceback

from std_msgs.msg import String

from waltzing_robot.waypoint_follower import WaypointFollower

class MetaWPExecutor(object):

    """Reads a meta wp config file and executes the trajectory in series """

    def __init__(self):
        self._wp_follower = WaypointFollower()
        self.waypoint_config_files = rospy.get_param('~waypoint_config_files', None)
        scripts_dir = os.path.abspath(os.path.dirname(__file__))
        main_dir = os.path.dirname(scripts_dir)
        self._waypoints_folder_path = os.path.join(main_dir, 'config/waypoints')
        self._in_motion = False

    def execute_meta_wp_trajectory(self):
        for wp_config in self.waypoint_config_files:
            waypoint_config_filename = os.path.join(self._waypoints_folder_path,
                                                    wp_config + '.yaml')
            print("\n"*3, "Starting", wp_config, "\n"*3)
            self._in_motion = True

            try:
                self._wp_follower.follow_waypoints(waypoint_config_filename)
            except Exception as e:
                rospy.logerr(str(e))
                traceback.print_exc()
                self._wp_follower.publish_zero_vel()

            print("\n"*3, "Finished", "\n"*3)

if __name__ == "__main__":
    rospy.init_node('meta_wp_executor')
    MWPE = MetaWPExecutor()
    MWPE.execute_meta_wp_trajectory()
