#! /usr/bin/env python

from __future__ import print_function

import os
import yaml
import rospy
import traceback

from std_msgs.msg import String

from waltzing_robot.waypoint_follower import WaypointFollower

class MetaWPExecutor(object):

    """Reads a meta wp config file and executes the trajectory in series """

    def __init__(self):
        self._wp_follower = WaypointFollower()
        scripts_dir = os.path.abspath(os.path.dirname(__file__))
        main_dir = os.path.dirname(scripts_dir)
        self._waypoints_folder_path = os.path.join(main_dir, 'config/waypoints')
        self._meta_waypoints_folder_path = os.path.join(main_dir, 'config/meta_waypoints')
        self._in_motion = False

        trigger_sub = rospy.Subscriber('~meta_wp_file_name', String, self.trigger_cb)
        rospy.loginfo('Initialised')

    def execute_meta_wp_trajectory(self, meta_wp_config_file_name='meta_test'):
        # read meta config file
        meta_wp_config_file = os.path.join(self._meta_waypoints_folder_path,
                                           meta_wp_config_file_name + '.yaml')
        with open(meta_wp_config_file, 'r') as file_obj:
            data = yaml.safe_load(file_obj)
        waypoint_config_files = data.get('waypoint_config_files', [])

        # iterate over config files and execute each one
        for wp_config in waypoint_config_files:
            waypoint_config_filename = os.path.join(self._waypoints_folder_path,
                                                    wp_config + '.yaml')
            print("\n"*3, "Starting", wp_config, "\n"*3)
            self._in_motion = True

            try:
                self._wp_follower.follow_waypoints(waypoint_config_filename)
            except Exception as e:
                rospy.logerr(str(e))
                traceback.print_exc()
                self._wp_follower.publish_zero_vel()

            print("\n"*3, "Finished", "\n"*3)

        self._in_motion = False

    def trigger_cb(self, msg):
        if self._in_motion:
            rospy.logwarn("Robot in motion. Ignoring request")
            return
        self.execute_meta_wp_trajectory(msg.data)

if __name__ == "__main__":
    rospy.init_node('meta_wp_executor')
    MWPE = MetaWPExecutor()
    rospy.spin()
