#! /usr/bin/env python

from __future__ import print_function

import rospy
import traceback

from waltzing_robot.waypoint_follower import WaypointFollower

def main():
    rospy.init_node('waltzer')
    wp_follower = WaypointFollower()
    try:
        remaining_loop = rospy.get_param('~num_of_loop', 1)
        waypoint_config_filename = rospy.get_param('~waypoint_config_filename', None)
        print(waypoint_config_filename)
        success = True
        while remaining_loop != 0 and success:
            success = wp_follower.follow_waypoints(waypoint_config_filename)
            remaining_loop -= 1
    except Exception as e:
        rospy.logerr(str(e))
        traceback.print_exc()
        wp_follower.publish_zero_vel()

if __name__ == "__main__":
    main()
